site_name: 2020_5CI_Team4_Software_Doc
nav:
    - 'Project Charter': 'Project_Charter_Doc.md'
    - 'Software Requirements Specification': 'Software Project Management Plan.md'
    - 'Software Project Management plan': 'Software Project Management Plan.md'
 
    
theme:
    name: readthedocs

use_directory_urls: true
