site_name: 2020_5CI_Team4_Software_Doc
nav:
    - 'Project Charter': 'Project_Charter_Doc.md'
    - 'Software Requirements Specification': 'Software Project Management Plan.md'
    - 'Software Project Management plan': 'Software Project Management Plan.md'
    - 'Business Model Canvas pdf': 'business_model_canvas_poster.pdf'
    - 'Project Model Canvas pdf': 'Project_Model_Canvas.pdf'
    - 'Project Charter pdf': 'Project_Charter_Doc.pdf'
    - 'Software Requirements Specification pdf': 'Software Project Management Plan.pdf'
    - 'Software Project Management plan pdf': 'Software Project Management Plan.pdf'
    - 'Iteration Plan': 'iteration_plan.md'
    - 'Iteration Plan pdf': 'iteration_plan.pdf'
    - 'Project Success Criteria': 'Project_Success_Criteria.md'
    - 'Project Success Criteria pdf': 'Project_Success_Criteria.pdf'
    - 'Release Plan': 'Release_Plan.md'
    - 'Release Plan pdf': 'Release_Plan.pdf'
    - 'Test Case Specification': 'Test_Case_Specification.md'
    - 'Test Case Specification pdf': 'Test_Case_Specification.pdf'
    - 'Test Plan': 'test_plan.md'
    - 'Test Plan pdf': 'test_plan.pdf'
    
theme:
    name: readthedocs

use_directory_urls: true
